name: Run Get Greeting 2

on: [repository_dispatch]

jobs:
  demo-get-greeting-2:
    if: github.event.action == 'get_greeting_2'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Demo Workflow "Get Greeting 2"
        uses: jwulf/zeebe-action@master
        with:
          client_config: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployWorkflow
          bpmn_filename: bpmn/demo-get-greeting-2.bpmn
      - name: Execute Demo Workflow "Get Greeting 2"
        uses: jwulf/zeebe-action@master
        with:
          operation: startWorkers
          worker_handler_file: workers/greeting.js
          worker_lifetime_mins: 2
