name: Deploy Workflows

on: [repository_dispatch]

jobs:
  deploy-workflows:
    if: github.event.action == 'start_workers'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start Workers
        uses: jwulf/zeebe-action@master
        with:
          client_config: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: startWorkers
          worker_handler_file: workers/workers.js
          worker_lifetime_mins: 2
